name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Build
      run: ./gradlew build

    - store_artifacts:
        path: app/build/reports
        destination: reports

    - name: Run Tests
      run: ./gradlew lint test

    - run:
        name: Run Tests
        command: ./gradlew lint test

    - store_test_results:
        path: app/build/test-results

    - store_artifacts:
        path: app/build/outputs/apk/debug/
        destination: artifact-file
